version: 2

models:
  - name: mart_sales_performance
    description: "Monthly sales performance by category"
    columns:
      - name: order_year
        description: "Year when the order was placed"
        tests:
          - not_null

      - name: order_month
        description: "Month when the order was placed"
        tests:
          - not_null

      - name: category_name
        description: "Product category"
        tests:
          - not_null

      - name: total_revenue
        description: "Sum of revenue for that period and category"
        tests:
          - not_null

      - name: total_orders
        description: "Number of distinct orders for that period and category"
        tests:
          - not_null

      - name: avg_revenue_per_order
        description: "Average revenue per order for that period and category"
        tests:
          - not_null
